CREATE TABLE IF NOT EXISTS `dataquestjson` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Name` varchar(255) NOT NULL,
  `Description` text DEFAULT NULL,
  `Summary` text DEFAULT NULL,
  `Story` text DEFAULT NULL,
  `Conclusion` text DEFAULT NULL,
  `NpcName` text NOT NULL,
  `NpcRegion` smallint(5) unsigned NOT NULL DEFAULT 0,
  `MaxCount` smallint(5) unsigned NOT NULL DEFAULT 0,
  `MinLevel` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `MaxLevel` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `RewardMoney` bigint(20) NOT NULL DEFAULT 0,
  `RewardXP` bigint(20) NOT NULL DEFAULT 0,
  `RewardCLXP` int(11) NOT NULL DEFAULT 0,
  `RewardRP` int(11) NOT NULL DEFAULT 0,
  `RewardBP` int(11) NOT NULL DEFAULT 0,
  `OptionalRewardItemTemplates` text DEFAULT NULL,
  `FinalRewardItemTemplates` text DEFAULT NULL,
  `QuestDependency` text DEFAULT NULL,
  `NotQuestDependency` text DEFAULT NULL,
  `AllowedClasses` text DEFAULT NULL,
  `GoalsJson` text NOT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `NbChooseOptionalItems` int(11) NOT NULL DEFAULT 0,
  `RewardBreamorFaction` int(11) NOT NULL DEFAULT 0,
  `isDaily` tinyint(1) NOT NULL DEFAULT 0,
  `CreatorAccount` varchar(100) NOT NULL DEFAULT 'System',
  PRIMARY KEY (`Id`),
  INDEX `idx_creator_account` (`CreatorAccount`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;
