export const DaocItemSlots = [
	{ id: 1, name: "Ground" },
	{ id: 10, name: "Right Hand" },
	{ id: 11, name: "Left Hand" },
	{ id: 12, name: "Two Hand" },
	{ id: 13, name: "Ranged" },
	{ id: 21, name: "Helm" },
	{ id: 22, name: "Hands" },
	{ id: 23, name: "Feet" },
	{ id: 24, name: "Jewellery" },
	{ id: 25, name: "Torso" },
	{ id: 26, name: "Cloak" },
	{ id: 27, name: "Legs" },
	{ id: 28, name: "Arms" },
	{ id: 29, name: "Necklace" },
	{ id: 30, name: "Bracers" },
	{ id: 31, name: "Shield" },
	{ id: 32, name: "Waist" },
	{ id: 33, name: "Left Wrist" },
	{ id: 34, name: "Right Wrist" },
	{ id: 35, name: "Left Ring" },
	{ id: 36, name: "Right Ring" },
	{ id: 37, name: "Mythical" },
	{ id: 40, name: "Backpack Begin" },
	{ id: 80, name: "Backpack End" },
	{ id: 100, name: "Paper-doll" },
];

export const DaocItemObjectTypes = [
	{ id: 0, name: "Generic Item (Junk/Loot/...)" },
	{ id: 1, name: "Generic Weapon" },
	{ id: 2, name: "Crushing Weapon (Albion)" },
	{ id: 3, name: "Slashing Weapon (Albion)" },
	{ id: 4, name: "Thrust Weapon (Albion)" },
	{ id: 5, name: "Fired Weapon (Albion)" },
	{ id: 6, name: "Two-Handed (Albion)" },
	{ id: 7, name: "Pole-arm Weapon (Albion)" },
	{ id: 8, name: "Staff (Albion)" },
	{ id: 9, name: "Longbow (Albion)" },
	{ id: 10, name: "Crossbow (Albion)" },
	{ id: 11, name: "Sword (Midgard)" },
	{ id: 12, name: "Hammer (Midgard)" },
	{ id: 13, name: "Axe (Midgard)" },
	{ id: 14, name: "Spear (Midgard)" },
	{ id: 15, name: "Composite Bow (Midgard)" },
	{ id: 16, name: "Thrown Weapon (Midgard)" },
	{ id: 17, name: "Left Axe (Midgard)" },
	{ id: 18, name: "Recurve Bow (Hibernia)" },
	{ id: 19, name: "Blades Weapon (Hibernia)" },
	{ id: 20, name: "Blunt Weapon (Hibernia)" },
	{ id: 21, name: "Piercing Weapon (Hibernia)" },
	{ id: 22, name: "Large Weapon (Hibernia)" },
	{ id: 23, name: "Celtic Spear (Hibernia)" },
	{ id: 24, name: "Flexible Weapon (Albion)" },
	{ id: 25, name: "Hand to Hand (Midgard)" },
	{ id: 26, name: "Scythe (Hibernia)" },
	{ id: 27, name: "Fist Wraps (Hibernia)" },
	{ id: 28, name: "Mauler Staff (Hibernia)" },

	{ id: 31, name: "Generic Armor" },
	{ id: 32, name: "Cloth Armor" },
	{ id: 33, name: "Leather Armor" },
	{ id: 34, name: "Studded Armor" },
	{ id: 35, name: "Chain Armor" },
	{ id: 36, name: "Plate Armor" },
	{ id: 37, name: "Reinforced Armor" },
	{ id: 38, name: "Scale Armor" },

	{ id: 41, name: "Magical Item" },
	{ id: 42, name: "Shield" },
	{ id: 43, name: "Arrow" },
	{ id: 44, name: "Bolt" },
	{ id: 45, name: "Instrument" },
	{ id: 46, name: "Poison" },
	{ id: 47, name: "Alchemy Tincture" },
	{ id: 48, name: "Spell-craft Gem" },

	{ id: 49, name: "Garden Object" },
	{ id: 50, name: "House Wall Object" },
	{ id: 51, name: "House Floor Object" },
	{ id: 52, name: "House Carpet First" },
	{ id: 53, name: "House NPC" },
	{ id: 54, name: "House Vault" },
	{ id: 55, name: "House Interior Object (Lathe, forge, alchemy table)" },
	{ id: 56, name: "House Tent Color" },
	{ id: 57, name: "House Exterior Banner" },
	{ id: 58, name: "House Exterior Shield" },
	{ id: 59, name: "House Roof Material" },
	{ id: 60, name: "House Wall Material" },
	{ id: 61, name: "House Door Material" },
	{ id: 62, name: "House Porch Material" },
	{ id: 63, name: "House Wood Material" },
	{ id: 64, name: "House Shutter Material" },
	{ id: 66, name: "House Interior Banner" },
	{ id: 67, name: "House Interior Shield" },
	{ id: 68, name: "House Bind-stone" },
	{ id: 69, name: "House Carpet Second" },
	{ id: 70, name: "House Carpet Third" },
	{ id: 71, name: "House Carpet Fourth" },

	{ id: 80, name: "Siege Ballista" }, // need log
	{ id: 81, name: "Siege Catapult" }, // need log
	{ id: 82, name: "Siege Cauldron" }, // need log
	{ id: 83, name: "Siege Ram" }, // need log
	{ id: 84, name: "Siege Trebuchet" }, // need log
];

export const DaocItemEffects = [
	{ value: 0, title: "none" },
	{ value: 1, title: "univ longsword propane-style flame" },
	{ value: 2, title: "univ longsword regular flame" },
	{ value: 3, title: "univ longsword orange flame" },
	{ value: 4, title: "univ longsword rising flame" },
	{ value: 5, title: "univ longsword flame w/smoke" },
	{ value: 6, title: "univ longsword flame w/sparks" },
	{ value: 7, title: "univ longsword hot glow" },
	{ value: 8, title: "univ longsword hot aura" },
	{ value: 9, title: "univ longsword blue aura" },
	{ value: 10, title: "univ longsword hot blue glow" },
	{ value: 11, title: "univ longsword hot gold glow" },
	{ value: 12, title: "univ longsword hot red glow" },
	{ value: 13, title: "univ longsword red aura" },
	{ value: 14, title: "univ longsword cold aura w/sparkles" },
	{ value: 15, title: "univ longsword cold aura w/vapor" },
	{ value: 16, title: "longsword hilt wavering blue beam" },
	{ value: 17, title: "longsword hilt wavering green beam" },
	{ value: 18, title: "longsword hilt wavering red beam" },
	{ value: 19, title: "longsword hilt red/blue beam" },
	{ value: 20, title: "longsword hilt purple beam" },
	{ value: 21, title: "univ 2h/gr sword yellow flames" },
	{ value: 22, title: "univ 2h/gr sword orange flames" },
	{ value: 23, title: "univ 2h/gr sword fire w/smoke" },
	{ value: 24, title: "univ 2h/gr sword fire w/sparks" },
	{ value: 25, title: "univ 2h/gr blue glow w/sparkles" },
	{ value: 26, title: "univ 2h/gr blue aura w/cold vapor" },
	{ value: 27, title: "univ 2h/gr icy blue glow" },
	{ value: 28, title: "univ 2h/gr red aura" },
	{ value: 29, title: "univ 2h/gr strong crimson glow" },
	{ value: 30, title: "univ 2h/gr white core red glow" },
	{ value: 31, title: "univ 2h/gr silvery/white glow" },
	{ value: 32, title: "univ 2h/gr gold/yellow glow" },
	{ value: 33, title: "univ 2h/gr hot green glow" },
	{ value: 34, title: "univ 1h hammer red aura" },
	{ value: 35, title: "univ 1h hammer fiery glow" },
	{ value: 36, title: "univ 1h hammer more intense fiery glow" },
	{ value: 37, title: "univ 1h hammer flaming" },
	{ value: 38, title: "univ 1h hammer torchlike flaming" },
	{ value: 39, title: "univ 1h hammer silvery glow" },
	{ value: 40, title: "univ 1h hammer purple glow" },
	{ value: 41, title: "univ 1h hammer blue aura" },
	{ value: 42, title: "univ 1h hammer blue glow" },
	{ value: 43, title: "univ 1h hammer arcs from head to handle" },
	{ value: 44, title: "univ 1h crush arcing halo" },
	{ value: 45, title: "univ 1h crush center arcing" },
	{ value: 46, title: "univ 1h crush smaller arcing halo" },
	{ value: 47, title: "univ 1h crush hot orange core glow" },
	{ value: 48, title: "univ 1h crush orange aura" },
	{ value: 49, title: "univ 1h crush subtle aura with sparks" },
	{ value: 50, title: "univ 1h crush yellow flame" },
	{ value: 51, title: "univ 1h crush mana flame" },
	{ value: 52, title: "univ 1h crush hot green glow" },
	{ value: 53, title: "univ 1h crush hot red glow" },
	{ value: 54, title: "univ 1h crush hot purple glow" },
	{ value: 55, title: "univ 1h crush cold vapor" },
	{ value: 56, title: "univ 1h axe basic flame" },
	{ value: 57, title: "univ 1h axe orange flame" },
	{ value: 58, title: "univ 1h axe slow orange flame w/sparks" },
	{ value: 59, title: "univ 1h axe fiery/trailing flame" },
	{ value: 60, title: "univ 1h axe cold vapor" },
	{ value: 61, title: "univ 1h axe blue aura with twinkles" },
	{ value: 62, title: "univ 1h axe hot green glow" },
	{ value: 63, title: "univ 1h axe hot blue glow" },
	{ value: 64, title: "univ 1h axe hot cyan glow" },
	{ value: 65, title: "univ 1h axe hot purple glow" },
	{ value: 66, title: "univ 1h axe blue->purple->orange glow" },
	{ value: 67, title: "univ shortsword propane flame" },
	{ value: 68, title: "univ shortsword orange flame with sparks" },
	{ value: 69, title: "univ shortsword blue aura with twinkles" },
	{ value: 70, title: "univ shortsword green cloud with bubbles" },
	{ value: 71, title: "univ shortsword red aura with blood bubbles" },
	{ value: 72, title: "univ shortsword evil green glow" },
	{ value: 73, title: "univ shortsword black glow" },
	{ value: 74, title: "Midgard battlespear cold with twinkles" },
	{ value: 75, title: "Midgard battlespear evil green aura" },
	{ value: 76, title: "Midgard battlespear evil red aura" },
	{ value: 77, title: "Midgard battlespear flaming" },
	{ value: 78, title: "Midgard battlespear hot gold glow" },
	{ value: 79, title: "Midgard battlespear hot fire glow" },
	{ value: 80, title: "Midgard battlespear red aura" },
	{ value: 81, title: "Midgard lugged spear blue glow" },
	{ value: 82, title: "Midgard lugged spear hot blue glow" },
	{ value: 83, title: "Midgard lugged spear cold with twinkles" },
	{ value: 84, title: "Midgard lugged spear electric arcing" },
	{ value: 85, title: "Midgard lugged spear hot yellow flame" },
	{ value: 86, title: "Midgard lugged spear orange flame w/ sparks" },
	{ value: 87, title: "Midgard lugged spear orange to purple flame" },
	{ value: 88, title: "Midgard lugged spear hot purple flame" },
	{ value: 89, title: "Midgard lugged spear silvery glow" },
	{ value: 90, title: "Briton quarterstaff blue glow" },
	{ value: 91, title: "Briton quarterstaff blue glow w/ twinkles" },
	{ value: 92, title: "Briton quarterstaff gold glow" },
	{ value: 93, title: "Briton quarterstaff gold glow w/ twinkles" },
	{ value: 94, title: "Briton quarterstaff faint red glow" },
	{ value: 95, title: "Relic pad effect" },
	{ value: 96, title: "Admorenths Staff Effect (Admorenth ONLY)" },
	{ value: 256, title: "Paladin Epic Two Handed Slash" },
	{ value: 257, title: "Hero Epic Blunt" },
	{ value: 258, title: "Warrior Epic One Handed Axe" },
	{ value: 259, title: "Hero_Piercing_2H" },
	{ value: 260, title: "Hero_Spear_2H" },
	{ value: 261, title: "Hero_Spear_1H" },
	{ value: 262, title: "Hero_Piercing_1H" },
	{ value: 263, title: "Hero_Blunt_2H" },
	{ value: 264, title: "Hero_Blade_2H" },
	{ value: 265, title: "Hero_Blade_1H" },
	{ value: 266, title: "Reaver_Sword_1H" },
	{ value: 267, title: "palladin_Slash_1h" },
	{ value: 268, title: "palladin_Thrust_2H" },
	{ value: 269, title: "palladin_Thrust_1H" },
	{ value: 270, title: "Reaver_Thrust_1H" },
	{ value: 271, title: "Reaver_Crush_1H" },
	{ value: 272, title: "Warrior_Sword_1H" },
	{ value: 273, title: "Warrior_Hammer_2H" },
	{ value: 274, title: "Warrior_Hammer_1H" },
	{ value: 275, title: "Warrior_Axe_2H" },
	{ value: 276, title: "Warrior_Sword_2H" },
	{ value: 277, title: "Reaver_Flex_1H" },
	{ value: 278, title: "palladin_Crush_2H" },
	{ value: 279, title: "palladin_Crush_1H" },
	{ value: 280, title: "Armsman_Thrust_2H" },
	{ value: 281, title: "Armsman_Crush_1H" },
	{ value: 282, title: "Armsman_Crush_2H" },
	{ value: 283, title: "Armsman_Pole_S" },
	{ value: 284, title: "Armsman_Sword_1H" },
	{ value: 285, title: "Armsman_Sword_2H" },
	{ value: 286, title: "Armsman_Thrust_1H" },
	{ value: 287, title: "Mercenary_T" },
	{ value: 288, title: "Mercenary_C" },
	{ value: 289, title: "Mercenary_S" },
	{ value: 290, title: "minstrel_T" },
	{ value: 291, title: "minstrel_S" },
	{ value: 292, title: "minstrel_H" },
	{ value: 293, title: "infiltrator_T" },
	{ value: 294, title: "Infiltrator_S" },
	{ value: 295, title: "sfx_epic_wpn_Armsman_Pole_C" },
	{ value: 296, title: "Heretic_flexS_1H" },
	{ value: 297, title: "Heretic_crush_1H" },
	{ value: 298, title: "Heretic_flexC_1H" },
	{ value: 299, title: "sfx_epic_wpn_cleric_C" },
	{ value: 300, title: "Scout_Bow" },
	{ value: 301, title: "Scout_T" },
	{ value: 302, title: "Scout_S" },
	{ value: 303, title: "sfx_epic_wpn_skald_axe_1h" },
	{ value: 304, title: "sfx_epic_wpn_skald_hammer_1h" },
	{ value: 305, title: "sfx_epic_wpn_skald_sword_1h" },
	{ value: 306, title: "sfx_epic_wpn_skald_hammer_2h" },
	{ value: 307, title: "sfx_epic_wpn_skald_axe_2h" },
	{ value: 308, title: "sfx_epic_wpn_skald_sword_2h" },
	{ value: 309, title: "sfx_epic_Druid_Crush_1H" },
	{ value: 310, title: "sfx_epic_Druid_Blade_1H" },
	{ value: 311, title: "sfx_epic_wpn_savage_sword_1h" },
	{ value: 312, title: "sfx_epic_wpn_savage_sword_2h" },
	{ value: 313, title: "sfx_epic_wpn_savage_axe_1h" },
	{ value: 314, title: "sfx_epic_Warden_Blade_1H" },
	{ value: 315, title: "sfx_epic_Warden_Crush_1H" },
	{ value: 316, title: "sfx_epic_Friar_Staff&amp;Crush" },
	{ value: 317, title: "sfx_epic_Necromancer_Staff" },
	{ value: 318, title: "sfx_epic_wpn_savage_axe_2h" },
	{ value: 319, title: "sfx_epic_wpn_savage_hth" },
	{ value: 320, title: "sfx_epic_wpn_savage_hammer_1h" },
	{ value: 321, title: "sfx_epic_wpn_savage_hammer_2h" },
	{ value: 322, title: "sfx_epic_wpn_valkyrie_sword_1h" },
	{ value: 323, title: "sfx_epic_wpn_valkyrie_sword_2h" },
	{ value: 324, title: "sfx_epic_Ranger_Bow" },
	{ value: 325, title: "sfx_epic_Ranger_Pierce_1H" },
	{ value: 326, title: "sfx_epic_Ranger_Slash_1H" },
	{ value: 327, title: "sfx_epic_wpn_valkyrie_spear" },
	{ value: 328, title: "sfx_epic_wpn_Sorcerer_St" },
	{ value: 329, title: "sfx_epic_wpn_hunter_sword_2h" },
	{ value: 330, title: "sfx_epic_wpn_hunter_sword_1H" },
	{ value: 331, title: "sfx_epic_wpn_hunter_spear" },
	{ value: 332, title: "sfx_epic_wpn_hunter_bow" },
	{ value: 333, title: "sfx_epic_Blademaster_Pierce_1H" },
	{ value: 334, title: "sfx_epic_Blademaster_Slash_1H" },
	{ value: 335, title: "sfx_epic_Blademaster_Crush_1H" },
	{ value: 336, title: "sfx_epic_wpn_thane_sword_2h" },
	{ value: 337, title: "sfx_epic_wpn_thane_sword_1h" },
	{ value: 338, title: "sfx_epic_wpn_thane_axe_2h" },
	{ value: 339, title: "sfx_epic_wpn_thane_axe_1h" },
	{ value: 340, title: "sfx_epic_Bainshee_Staff" },
	{ value: 341, title: "sfx_epic_Animist_Staff" },
	{ value: 342, title: "sfx_epic_Eldritch_Staff" },
	{ value: 343, title: "sfx_epic_Enchanter_Staff" },
	{ value: 344, title: "sfx_epic_wpn_thane_hammer_2h" },
	{ value: 345, title: "sfx_epic_wpn_thane_hammer_1h" },
	{ value: 346, title: "sfx_epic_wpn_shadowblade_sword_2h" },
	{ value: 347, title: "sfx_epic_wpn_shadowblade_sword_1h" },
	{ value: 348, title: "sfx_epic_Mentalist_Staff" },
	{ value: 349, title: "sfx_epic_Valewalker_Sy" },
	{ value: 350, title: "sfx_epic_wpn_shadowblade_axe_1h" },
	{ value: 351, title: "sfx_epic_wpn_shadowblade_axe_2h" },
	{ value: 352, title: "sfx_epic_Healer_Crush_2H" },
	{ value: 353, title: "sfx_epic_Healer_Crush_1H" },
	{ value: 354, title: "sfx_epic_Spiritmaster_Staff" },
	{ value: 355, title: "sfx_epic_wpn_Cabalist_st" },
	{ value: 356, title: "sfx_epic_wpn_Theurgist_St" },
	{ value: 357, title: "sfx_epic_wpn_Vampiir_T" },
	{ value: 358, title: "sfx_epic_wpn_Wizard_St" },
	{ value: 359, title: "sfx_epic_wpn_Runemaster_St" },
	{ value: 360, title: "sfx_epic_Shaman_Crush_1H" },
	{ value: 361, title: "sfx_epic_Bonedancer_Staff" },
	{ value: 362, title: "sfx_epic_Warlock_Staff" },
	{ value: 363, title: "sfx_epic_Shaman_Crush_2H" },
	{ value: 364, title: "sfx_epic_wpn_Champion_Slash_2h" },
	{ value: 365, title: "sfx_epic_wpn_Champion_Slash_1h" },
	{ value: 366, title: "sfx_epic_wpn_Champion_Pierce_1h" },
	{ value: 367, title: "sfx_epic_wpn_Champion_Crush_2h" },
	{ value: 368, title: "sfx_epic_wpn_Champion_Crush_1h" },
	{ value: 369, title: "sfx_epic_wpn_nightshade_T" },
	{ value: 370, title: "sfx_epic_wpn_nightshade_S" },
	{ value: 371, title: "sfx_epic_wpn_berserker_axe_2h" },
	{ value: 372, title: "sfx_epic_wpn_berserker_axe_1h" },
	{ value: 373, title: "sfx_epic_wpn_berserker_sword_2h" },
	{ value: 374, title: "sfx_epic_wpn_berserker_sword_1h" },
	{ value: 375, title: "sfx_epic_wpn_berserker_hammer_2h" },
	{ value: 376, title: "sfx_epic_wpn_berserker_hammer_1h" },
	{ value: 377, title: "sfx_epic_wpn_Bard_Blade_1H" },
	{ value: 378, title: "sfx_epic_wpn_Bard_Crush_1H" },
	{ value: 379, title: "sfx_epic_wpn_Bard_Harp" },
];

export const DaocColors = [
	{ value: 0, title: "White", color: "rgb(255, 255, 255)" },
	{ value: 1, title: "Old Red", color: "rgb(255, 128, 64)" },
	{ value: 2, title: "Old Green", color: "rgb(128, 255, 128)" },
	{ value: 3, title: "Old Blue", color: "rgb(128, 200, 255)" },
	{ value: 4, title: "Old Yellow", color: "rgb(228, 228, 150)" },
	{ value: 5, title: "Old Purple", color: "rgb(255, 170, 255)" },
	{ value: 6, title: "Gray", color: "rgb(128, 128, 128)" },
	{ value: 7, title: "Old Turquoise", color: "rgb(128, 255, 255)" },
	{ value: 8, title: "Leather Yellow", color: "rgb(255, 243, 63)" },
	{ value: 9, title: "Leather Red", color: "rgb(222, 84, 84)" },
	{ value: 10, title: "Leather Green", color: "rgb(143, 195, 152)" },
	{ value: 11, title: "Leather Orange", color: "rgb(255, 193, 93)" },
	{ value: 12, title: "Leather Violet", color: "rgb(152, 109, 144)" },
	{ value: 13, title: "Leather Forest Green", color: "rgb(143, 195, 152)" },
	{ value: 14, title: "Leather Blue", color: "rgb(123, 185, 255)" },
	{ value: 15, title: "Leather Purple", color: "rgb(123, 123, 255)" },
	{ value: 16, title: "Bronze", color: "rgb(200, 164, 110)" },
	{ value: 17, title: "Iron", color: "rgb(125, 126, 133)" },
	{ value: 18, title: "Steel", color: "rgb(112, 140, 151)" },
	{ value: 19, title: "Alloy", color: "rgb(123, 113, 97)" },
	{ value: 20, title: "Fine Alloy", color: "rgb(173, 159, 137)" },
	{ value: 21, title: "Mithril", color: "rgb(164, 207, 184)" },
	{ value: 22, title: "Asterite", color: "rgb(210, 155, 51)" },
	{ value: 23, title: "Eog", color: "rgb(156, 193, 127)" },
	{ value: 24, title: "Xenium", color: "rgb(216, 77, 77)" },
	{ value: 25, title: "Vaanum", color: "rgb(213, 211, 159)" },
	{ value: 26, title: "Adamantium", color: "rgb(20, 20, 60)" },
	{ value: 27, title: "Red Cloth", color: "rgb(223, 0, 41)" },
	{ value: 28, title: "Orange Cloth", color: "rgb(231, 101, 26)" },
	{ value: 29, title: "Yellow-Orange Cloth", color: "rgb(238, 156, 0)" },
	{ value: 30, title: "Yellow Cloth", color: "rgb(249, 244, 0)" },
	{ value: 31, title: "Yellow-Green Cloth", color: "rgb(125, 198, 34)" },
	{ value: 32, title: "Green Cloth", color: "rgb(0, 176, 59)" },
	{ value: 33, title: "Blue-Green Cloth", color: "rgb(0, 159, 98)" },
	{ value: 34, title: "Turquoise Cloth", color: "rgb(0, 164, 158)" },
	{ value: 35, title: "Light Blue Cloth", color: "rgb(0, 178, 235)" },
	{ value: 36, title: "Blue Cloth", color: "rgb(0, 105, 179)" },
	{ value: 37, title: "Blue-Violet Cloth", color: "rgb(50, 67, 149)" },
	{ value: 38, title: "Violet Cloth", color: "rgb(61, 17, 123)" },
	{ value: 39, title: "Bright Violet Cloth", color: "rgb(102, 9, 123)" },
	{ value: 40, title: "Purple Cloth", color: "rgb(146, 0, 123)" },
	{ value: 41, title: "Bright Purple Cloth", color: "rgb(226, 0, 127)" },
	{ value: 42, title: "Purple-Red Cloth", color: "rgb(225, 0, 87)" },
	{ value: 43, title: "Black Cloth", color: "rgb(34, 47, 45)" },
	{ value: 44, title: "Brown Cloth", color: "rgb(122, 75, 29)" },
	{ value: 45, title: "Blue Metal", color: "rgb(122, 122, 160)" },
	{ value: 46, title: "Green Metal", color: "rgb(83, 129, 83)" },
	{ value: 47, title: "Yellow Metal", color: "rgb(152, 141, 102)" },
	{ value: 48, title: "Gold Metal", color: "rgb(147, 122, 36)" },
	{ value: 49, title: "Red Metal", color: "rgb(127, 56, 56)" },
	{ value: 50, title: "Purple Metal", color: "rgb(121, 109, 123)" },
	{ value: 51, title: "Blue 1", color: "rgb(60, 120, 210)" },
	{ value: 52, title: "Blue 2", color: "rgb(45, 90, 215)" },
	{ value: 53, title: "Blue 3", color: "rgb(15, 45, 220)" },
	{ value: 54, title: "Blue 4", color: "rgb(0, 50, 100)" },
	{ value: 55, title: "Turquoise 1", color: "rgb(90, 200, 180)" },
	{ value: 56, title: "Turquoise 2", color: "rgb(55, 180, 160)" },
	{ value: 57, title: "Turquoise 3", color: "rgb(20, 140, 120)" },
	{ value: 58, title: "Teal 1", color: "rgb(50, 130, 145)" },
	{ value: 59, title: "Teal 2", color: "rgb(30, 110, 135)" },
	{ value: 60, title: "Teal 3", color: "rgb(10, 90, 125)" },
	{ value: 61, title: "Brown 1", color: "rgb(200, 160, 100)" },
	{ value: 62, title: "Brown 2", color: "rgb(170, 130, 70)" },
	{ value: 63, title: "Brown 3", color: "rgb(125, 85, 25)" },
	{ value: 64, title: "Red 1", color: "rgb(190, 85, 85)" },
	{ value: 65, title: "Red 2", color: "rgb(200, 55, 55)" },
	{ value: 66, title: "Red 3", color: "rgb(210, 25, 25)" },
	{ value: 67, title: "Red 4", color: "rgb(140, 10, 10)" },
	{ value: 68, title: "Green 1", color: "rgb(100, 160, 100)" },
	{ value: 69, title: "Green 2", color: "rgb(70, 140, 70)" },
	{ value: 70, title: "Green 3", color: "rgb(40, 120, 40)" },
	{ value: 71, title: "Green 4", color: "rgb(0, 150, 75)" },
	{ value: 72, title: "Gray 1", color: "rgb(100, 100, 100)" },
	{ value: 73, title: "Gray 2", color: "rgb(65, 65, 65)" },
	{ value: 74, title: "Gray 3", color: "rgb(30, 30, 30)" },
	{ value: 75, title: "Orange 1", color: "rgb(255, 160, 0)" },
	{ value: 76, title: "Orange 2", color: "rgb(240, 120, 15)" },
	{ value: 77, title: "Orange 3", color: "rgb(225, 80, 30)" },
	{ value: 78, title: "Purple 1", color: "rgb(160, 100, 190)" },
	{ value: 79, title: "Purple 2", color: "rgb(140, 60, 200)" },
	{ value: 80, title: "Purple 3", color: "rgb(120, 20, 210)" },
	{ value: 81, title: "Yellow 1", color: "rgb(180, 180, 90)" },
	{ value: 82, title: "Yellow 2", color: "rgb(195, 195, 60)" },
	{ value: 83, title: "Yelow 3", color: "rgb(215, 215, 30)" },
	{ value: 84, title: "violet", color: "rgb(230, 40, 230)" },
	{ value: 85, title: "mauve", color: "rgb(160, 20, 90)" },
	{ value: 86, title: "Blue 4", color: "rgb(25, 25, 150)" },
	{ value: 87, title: "Purple 4", color: "rgb(90, 10, 180)" },
	{ value: 100, title: "Ship Red", color: "rgb(203, 91, 91)" },
	{ value: 101, title: "Ship Red 2", color: "rgb(191, 106, 106)" },
	{ value: 102, title: "Ship Orange", color: "rgb(204, 161, 82)" },
	{ value: 103, title: "Ship Orange 2", color: "rgb(204, 138, 102)" },
	{ value: 104, title: "Orange 3", color: "rgb(225, 80, 30)" },
	{ value: 105, title: "Ship Yellow", color: "rgb(229, 229, 114)" },
	{ value: 106, title: "Ship Lime Green", color: "rgb(211, 255, 128)" },
	{ value: 107, title: "Ship Green", color: "rgb(187, 255, 152)" },
	{ value: 108, title: "Ship Green 2", color: "rgb(153, 255, 153)" },
	{ value: 109, title: "Ship Turquiose", color: "rgb(141, 255, 216)" },
	{ value: 110, title: "Ship Turqiose 2", color: "rgb(154, 255, 189)" },
	{ value: 111, title: "Ship Blue", color: "rgb(166, 255, 255)" },
	{ value: 112, title: "Ship Blue 2", color: "rgb(188, 211, 255)" },
	{ value: 113, title: "Ship Blue 3", color: "rgb(166, 197, 255)" },
	{ value: 114, title: "Ship Purple", color: "rgb(188, 188, 255)" },
	{ value: 115, title: "Ship Purple 2", color: "rgb(211, 188, 255)" },
	{ value: 116, title: "Ship Purple 3", color: "rgb(232, 188, 255)" },
	{ value: 117, title: "Ship Pink", color: "rgb(204, 122, 122)" },
	{ value: 118, title: "Ship Charcoal", color: "rgb(141, 141, 141)" },
	{ value: 119, title: "Ship Charcoal 2", color: "rgb(190, 190, 190)" },
	{ value: 120, title: "red - crafter only", color: "rgb(255, 53, 58)" },
	{ value: 121, title: "plum - crafter only", color: "rgb(116, 0, 67)" },
	{ value: 122, title: "purple - crafter only", color: "rgb(99, 4, 96)" },
	{ value: 123, title: "dark purple - crafter only", color: "rgb(68, 4, 98)" },
	{ value: 124, title: "dusky purple - crafter only", color: "rgb(152, 136, 165)" },
	{ value: 125, title: "light gold - crafter only", color: "rgb(236, 232, 98)" },
	{ value: 126, title: "dark gold - crafter only", color: "rgb(144, 114, 0)" },
	{ value: 127, title: "dirty orange - crafter only", color: "rgb(227, 181, 85)" },
	{ value: 128, title: "dark tan - crafter only", color: "rgb(175, 161, 134)" },
	{ value: 129, title: "brown - crafter only", color: "rgb(107, 78, 20)" },
	{ value: 130, title: "light green - crafter only", color: "rgb(135, 196, 129)" },
	{ value: 131, title: "olive green - crafter only", color: "rgb(78, 89, 10)" },
	{ value: 132, title: "cornflower blue - crafter only", color: "rgb(143, 162, 204)" },
	{ value: 133, title: "light gray - crafter only", color: "rgb(154, 154, 154)" },
	{ value: 134, title: "hot pink - crafter only", color: "rgb(255, 0, 255)" },
	{ value: 135, title: "dusky rose - crafter only", color: "rgb(230, 145, 217)" },
	{ value: 136, title: "sage green - crafter only", color: "rgb(170, 199, 167)" },
	{ value: 137, title: "lime green - crafter only", color: "rgb(114, 255, 0)" },
	{ value: 138, title: "gray teal - crafter only", color: "rgb(120, 160, 160)" },
	{ value: 139, title: "gray blue - crafter only", color: "rgb(90, 97, 152)" },
	{ value: 140, title: "olive gray - crafter only", color: "rgb(128, 128, 128)" },
	{ value: 141, title: "Navy Blue - crafter only", color: "rgb(0, 0, 74)" },
	{ value: 142, title: "Forest Green - crafter only", color: "rgb(0, 64, 0)" },
	{ value: 143, title: "Burgundy - crafter only", color: "rgb(85, 0, 0)" },
];

export const DaocItemExtension = [
	{ value: 0, title: "0. None" },
	{ value: 1, title: "1. Slight" },
	{ value: 2, title: "2. Some" },
	{ value: 3, title: "3. Medium" },
	{ value: 4, title: "4. Heavy" },
	{ value: 5, title: "5. Extra Heavy" },

	{ value: 6, title: "6. ?" },
	{ value: 7, title: "7. ?" },
	{ value: 8, title: "8. ?" },
	{ value: 9, title: "9. ?" },
	{ value: 10, title: "10. ?" },
	{ value: 11, title: "11. ?" },
	{ value: 12, title: "12. ?" },
];

export const DaocItemHand = [
	{ value: 0, title: "0. Right" },
	{ value: 1, title: "1. Two handed" },
	{ value: 2, title: "2. Left" },
];

export const DaocDamageType = [
	{ value: 0, title: "0. Natural" },
	{ value: 1, title: "1. Crush" },
	{ value: 2, title: "2. Slash" },
	{ value: 3, title: "3. Thrust" },
	{ value: 10, title: "10. Body" },
	{ value: 11, title: "11. Cold" },
	{ value: 12, title: "12. Energy" },
	{ value: 13, title: "13. Heat" },
	{ value: 14, title: "14. Matter" },
	{ value: 15, title: "15. Spirit" },
];

export const DaocProperty = [
	{ value: 0, title: "none" },

	{ value: 1, title: "Strength" },
	{ value: 2, title: "Dexterity" },
	{ value: 3, title: "Constitution" },
	{ value: 4, title: "Quickness" },
	{ value: 5, title: "Intelligence" },
	{ value: 6, title: "Piety" },
	{ value: 7, title: "Empathy" },
	{ value: 8, title: "Charisma" },

	{ value: 9, title: "MaxMana" },
	{ value: 10, title: "MaxHealth" },

	{ value: 11, title: "Resist_Body" },
	{ value: 12, title: "Resist_Cold" },
	{ value: 13, title: "Resist_Crush" },
	{ value: 14, title: "Resist_Energy" },
	{ value: 15, title: "Resist_Heat" },
	{ value: 16, title: "Resist_Matter" },
	{ value: 17, title: "Resist_Slash" },
	{ value: 18, title: "Resist_Spirit" },
	{ value: 19, title: "Resist_Thrust" },

	{ value: 20, title: "Skill_Two_Handed" },
	{ value: 21, title: "Skill_Body" },
	{ value: 22, title: "Skill_Chants" },
	{ value: 23, title: "Skill_Critical_Strike" },
	{ value: 24, title: "Skill_Cross_Bows" },
	{ value: 25, title: "Skill_Crushing" },
	{ value: 26, title: "Skill_Death_Servant" },
	{ value: 27, title: "Skill_DeathSight" },
	{ value: 28, title: "Skill_Dual_Wield" },
	{ value: 29, title: "Skill_Earth" },
	{ value: 30, title: "Skill_Enhancement" },
	{ value: 31, title: "Skill_Envenom" },
	{ value: 32, title: "Skill_Fire" },
	{ value: 33, title: "Skill_Flexible_Weapon" },
	{ value: 34, title: "Skill_Cold" },
	{ value: 35, title: "Skill_Instruments" },
	{ value: 36, title: "Skill_Long_bows" },
	{ value: 37, title: "Skill_Matter" },
	{ value: 38, title: "Skill_Mind" },
	{ value: 39, title: "Skill_Pain_working" },
	{ value: 40, title: "Skill_Parry" },
	{ value: 41, title: "Skill_Polearms" },
	{ value: 42, title: "Skill_Rejuvenation" },
	{ value: 43, title: "Skill_Shields" },
	{ value: 44, title: "Skill_Slashing" },
	{ value: 45, title: "Skill_Smiting" },
	{ value: 46, title: "Skill_SoulRending" },
	{ value: 47, title: "Skill_Spirit" },
	{ value: 48, title: "Skill_Staff" },
	{ value: 49, title: "Skill_Stealth" },
	{ value: 50, title: "Skill_Thrusting" },
	{ value: 51, title: "Skill_Wind" },
	{ value: 52, title: "Skill_Sword" },
	{ value: 53, title: "Skill_Hammer" },
	{ value: 54, title: "Skill_Axe" },
	{ value: 55, title: "Skill_Left_Axe" },
	{ value: 56, title: "Skill_Spear" },
	{ value: 57, title: "Skill_Mending" },
	{ value: 58, title: "Skill_Augmentation" },
	{ value: 59, title: "//Skill_Cave_Magic" },
	{ value: 60, title: "Skill_Darkness" },
	{ value: 61, title: "Skill_Suppression" },
	{ value: 62, title: "Skill_Runecarving" },
	{ value: 63, title: "Skill_Stormcalling" },
	{ value: 64, title: "Skill_BeastCraft" },
	{ value: 65, title: "Skill_Light" },
	{ value: 66, title: "Skill_Void" },
	{ value: 67, title: "Skill_Mana" },
	{ value: 68, title: "Skill_Composite" },
	{ value: 69, title: "Skill_Battlesongs" },
	{ value: 70, title: "Skill_Enchantments" },
	{ value: 72, title: "Skill_Blades" },
	{ value: 73, title: "Skill_Blunt" },
	{ value: 74, title: "Skill_Piercing" },
	{ value: 75, title: "Skill_Large_Weapon" },
	{ value: 76, title: "Skill_Mentalism" },
	{ value: 77, title: "Skill_Regrowth" },
	{ value: 78, title: "Skill_Nurture" },
	{ value: 79, title: "Skill_Nature" },
	{ value: 80, title: "Skill_Music" },
	{ value: 81, title: "Skill_Celtic_Dual" },
	{ value: 82, title: "Skill_Celtic_Spear" },
	{ value: 83, title: "Skill_RecurvedBow" },
	{ value: 84, title: "Skill_Valor" },
	{ value: 85, title: "Skill_Subterranean" },
	{ value: 86, title: "Skill_BoneArmy" },
	{ value: 87, title: "Skill_Verdant" },
	{ value: 88, title: "Skill_Creeping" },
	{ value: 89, title: "Skill_Arboreal" },
	{ value: 90, title: "Skill_Scythe" },
	{ value: 91, title: "Skill_Thrown_Weapons" },
	{ value: 92, title: "Skill_HandToHand" },
	{ value: 93, title: "Skill_ShortBow" },
	{ value: 94, title: "Skill_Pacification" },
	{ value: 95, title: "Skill_Savagery" },
	{ value: 96, title: "Skill_Nightshade" },
	{ value: 97, title: "Skill_Pathfinding" },
	{ value: 98, title: "Skill_Summoning" },
	{ value: 99, title: "Skill_Dementia" },
	{ value: 100, title: "Skill_ShadowMastery" },
	{ value: 101, title: "Skill_VampiiricEmbrace" },
	{ value: 102, title: "Skill_EtherealShriek" },
	{ value: 103, title: "Skill_PhantasmalWail" },
	{ value: 104, title: "Skill_SpectralForce" },
	{ value: 105, title: "Skill_OdinsWill" },
	{ value: 106, title: "Skill_Cursing" },
	{ value: 107, title: "Skill_Hexing" },
	{ value: 108, title: "Skill_Witchcraft" },
	{ value: 109, title: "Skill_MaulerStaff" },
	{ value: 110, title: "Skill_FistWraps" },
	{ value: 111, title: "Skill_Power_Strikes" },
	{ value: 112, title: "Skill_Magnetism" },
	{ value: 113, title: "Skill_Aura_Manipulation" },
	{ value: 114, title: "Skill_SpectralGuard" },
	{ value: 115, title: "Skill_Archery" },

	{ value: 120, title: "Focus_Darkness" },
	{ value: 121, title: "Focus_Suppression" },
	{ value: 122, title: "Focus_Runecarving" },
	{ value: 123, title: "Focus_Spirit" },
	{ value: 124, title: "Focus_Fire" },
	{ value: 125, title: "Focus_Air" },
	{ value: 126, title: "Focus_Cold" },
	{ value: 127, title: "Focus_Earth" },
	{ value: 128, title: "Focus_Light" },
	{ value: 129, title: "Focus_Body" },
	{ value: 130, title: "Focus_Matter" },
	{ value: 132, title: "Focus_Mind" },
	{ value: 133, title: "Focus_Void" },
	{ value: 134, title: "Focus_Mana" },
	{ value: 135, title: "Focus_Enchantments" },
	{ value: 136, title: "Focus_Mentalism" },
	{ value: 137, title: "Focus_Summoning" },
	{ value: 138, title: "Focus_BoneArmy" },
	{ value: 139, title: "Focus_PainWorking" },
	{ value: 140, title: "Focus_DeathSight" },
	{ value: 141, title: "Focus_DeathServant" },
	{ value: 142, title: "Focus_Verdant" },
	{ value: 143, title: "Focus_CreepingPath" },
	{ value: 144, title: "Focus_Arboreal" },
	{ value: 145, title: "MaxSpeed" },

	{ value: 147, title: "MaxConcentration" },
	{ value: 148, title: "ArmorFactor" },
	{ value: 149, title: "ArmorAbsorption" },
	{ value: 150, title: "HealthRegenerationRate" },
	{ value: 151, title: "PowerRegenerationRate" },
	{ value: 152, title: "EnduranceRegenerationRate" },
	{ value: 153, title: "SpellRange" },
	{ value: 154, title: "ArcheryRange" },
	{ value: 155, title: "MeleeSpeed" },
	{ value: 156, title: "Acuity" },
	{ value: 157, title: "Focus_EtherealShriek" },
	{ value: 158, title: "Focus_PhantasmalWail" },
	{ value: 159, title: "Focus_SpectralForce" },
	{ value: 160, title: "Focus_Cursing" },
	{ value: 161, title: "Focus_Hexing" },
	{ value: 162, title: "Focus_Witchcraft" },
	{ value: 163, title: "AllMagicSkills" },
	{ value: 164, title: "AllMeleeWeaponSkills" },
	{ value: 165, title: "AllFocusLevels" },
	{ value: 166, title: "LivingEffectiveLevel" },
	{ value: 167, title: "AllDualWieldingSkills" },
	{ value: 168, title: "AllArcherySkills" },
	{ value: 169, title: "EvadeChance" },
	{ value: 170, title: "BlockChance" },
	{ value: 171, title: "ParryChance" },
	{ value: 172, title: "FatigueConsumption" },
	{ value: 173, title: "MeleeDamage" },
	{ value: 174, title: "RangedDamage" },
	{ value: 175, title: "FumbleChance" },
	{ value: 176, title: "MesmerizeDurationReduction" },
	{ value: 177, title: "StunDurationReduction" },
	{ value: 178, title: "SpeedDecreaseDurationReduction" },
	{ value: 179, title: "BladeturnReinforcement" },
	{ value: 180, title: "DefensiveBonus" },
	{ value: 181, title: "SpellFumbleChance" },
	{ value: 182, title: "NegativeReduction" },
	{ value: 183, title: "PieceAblative" },
	{ value: 184, title: "ReactionaryStyleDamage" },
	{ value: 185, title: "SpellPowerCost" },
	{ value: 186, title: "StyleCostReduction" },
	{ value: 187, title: "ToHitBonus" },

	{ value: 188, title: "ArcherySpeed" },
	{ value: 189, title: "ArrowRecovery" },
	{ value: 190, title: "BuffEffectiveness" },
	{ value: 191, title: "CastingSpeed" },
	{ value: 192, title: "DeathExpLoss" },
	{ value: 193, title: "DebuffEffectivness" },
	{ value: 194, title: "Fatigue" },
	{ value: 195, title: "HealingEffectiveness" },
	{ value: 196, title: "PowerPool" },
	{ value: 197, title: "ResistPierce" },
	{ value: 198, title: "SpellDamage" },
	{ value: 199, title: "SpellDuration" },
	{ value: 200, title: "StyleDamage" },

	{ value: 201, title: "StrCapBonus" },
	{ value: 202, title: "DexCapBonus" },
	{ value: 203, title: "ConCapBonus" },
	{ value: 204, title: "QuiCapBonus" },
	{ value: 205, title: "IntCapBonus" },
	{ value: 206, title: "PieCapBonus" },
	{ value: 207, title: "EmpCapBonus" },
	{ value: 208, title: "ChaCapBonus" },
	{ value: 209, title: "AcuCapBonus" },
	{ value: 210, title: "MaxHealthCapBonus" },
	{ value: 211, title: "PowerPoolCapBonus" },

	{ value: 212, title: "WeaponSkill" },
	{ value: 213, title: "AllSkills" },
	{ value: 214, title: "CriticalMeleeHitChance" },
	{ value: 215, title: "CriticalArcheryHitChance" },
	{ value: 216, title: "CriticalSpellHitChance" },
	{ value: 217, title: "WaterSpeed" },
	{ value: 218, title: "SpellLevel" },
	{ value: 219, title: "MissHit" },
	{ value: 220, title: "KeepDamage" },

	{ value: 221, title: "BodyResCapBonus" },
	{ value: 222, title: "ColdResCapBonus" },
	{ value: 223, title: "CrushResCapBonus" },
	{ value: 224, title: "EnergyResCapBonus" },
	{ value: 225, title: "HeatResCapBonus" },
	{ value: 226, title: "MatterResCapBonus" },
	{ value: 227, title: "SlashResCapBonus" },
	{ value: 228, title: "SpiritResCapBonus" },
	{ value: 229, title: "ThrustResCapBonus" },

	{ value: 230, title: "DPS" },
	{ value: 231, title: "MagicAbsorption" },
	{ value: 232, title: "CriticalHealHitChance" },

	{ value: 233, title: "MythicalSafeFall" },
	{ value: 234, title: "MythicalDiscumbering" },
	{ value: 235, title: "MythicalCoin" },

	{ value: 236, title: "MythicalStrCapBonus" },
	{ value: 237, title: "MythicalDexCapBonus" },
	{ value: 238, title: "MythicalConCapBonus" },
	{ value: 239, title: "MythicalQuiCapBonus" },
	{ value: 240, title: "MythicalIntCapBonus" },
	{ value: 241, title: "MythicalPieCapBonus" },
	{ value: 242, title: "MythicalEmpCapBonus" },
	{ value: 243, title: "MythicalChaCapBonus" },
	{ value: 244, title: "MythicalAcuCapBonus" },

	{ value: 247, title: "BountyPoints" },
	{ value: 248, title: "XpPoints" },
	{ value: 249, title: "Resist_Natural" },
	{ value: 250, title: "ExtraHP" },
	{ value: 251, title: "Conversion" },
	{ value: 252, title: "StyleAbsorb" },
	{ value: 253, title: "RealmPoints" },
	{ value: 254, title: "ArcaneSyphon" },
	{ value: 255, title: "LivingEffectiveness" },
];

/**
 * Property ID constants matching DOL's eProperty enum.
 * Used for calculating item utility and identifying bonus types.
 */
export const eProperty = {
	Undefined: 0,

	// Stats (1-8)
	Stat_First: 1,
	Strength: 1,
	Dexterity: 2,
	Constitution: 3,
	Quickness: 4,
	Intelligence: 5,
	Piety: 6,
	Empathy: 7,
	Charisma: 8,
	Stat_Last: 8,

	// Special stats
	MaxMana: 9,
	MaxHealth: 10,

	// Resists (11-19)
	Resist_First: 11,
	Resist_Body: 11,
	Resist_Cold: 12,
	Resist_Crush: 13,
	Resist_Energy: 14,
	Resist_Heat: 15,
	Resist_Matter: 16,
	Resist_Slash: 17,
	Resist_Spirit: 18,
	Resist_Thrust: 19,
	Resist_Last: 19,

	// Skills (20-115)
	Skill_First: 20,
	Skill_Last: 115,

	// Focus (120-165)
	Focus_First: 120,
	Focus_Last: 165,

	// Misc properties
	MaxSpeed: 145,
	MaxConcentration: 147,
	ArmorFactor: 148,
	ArmorAbsorption: 149,
	HealthRegenerationRate: 150,
	PowerRegenerationRate: 151,
	EnduranceRegenerationRate: 152,
	SpellRange: 153,
	ArcheryRange: 154,
	MeleeSpeed: 155,
	Acuity: 156,
	LivingEffectiveLevel: 166,
	EvadeChance: 169,
	BlockChance: 170,
	ParryChance: 171,
	FatigueConsumption: 172,
	MeleeDamage: 173,
	RangedDamage: 174,
	FumbleChance: 175,
	MesmerizeDurationReduction: 176,
	StunDurationReduction: 177,
	SpeedDecreaseDurationReduction: 178,
	BladeturnReinforcement: 179,
	DefensiveBonus: 180,
	SpellFumbleChance: 181,
	NegativeReduction: 182,
	PieceAblative: 183,
	ReactionaryStyleDamage: 184,
	SpellPowerCost: 185,
	StyleCostReduction: 186,
	ToHitBonus: 187,

	// ToA Bonuses (188-200)
	ToABonus_First: 188,
	ArcherySpeed: 188,
	ArrowRecovery: 189,
	BuffEffectiveness: 190,
	CastingSpeed: 191,
	DeathExpLoss: 192,
	DebuffEffectivness: 193,
	Fatigue: 194,
	HealingEffectiveness: 195,
	PowerPool: 196,
	ResistPierce: 197,
	SpellDamage: 198,
	SpellDuration: 199,
	StyleDamage: 200,
	ToABonus_Last: 200,

	// Stat Cap Bonuses (201-211)
	StatCapBonus_First: 201,
	StrCapBonus: 201,
	DexCapBonus: 202,
	ConCapBonus: 203,
	QuiCapBonus: 204,
	IntCapBonus: 205,
	PieCapBonus: 206,
	EmpCapBonus: 207,
	ChaCapBonus: 208,
	AcuCapBonus: 209,
	MaxHealthCapBonus: 210,
	PowerPoolCapBonus: 211,
	StatCapBonus_Last: 211,

	WeaponSkill: 212,
	AllSkills: 213,
	CriticalMeleeHitChance: 214,
	CriticalArcheryHitChance: 215,
	CriticalSpellHitChance: 216,
	WaterSpeed: 217,
	SpellLevel: 218,
	MissHit: 219,
	KeepDamage: 220,

	// Resist Cap Bonuses (221-229)
	ResCapBonus_First: 221,
	BodyResCapBonus: 221,
	ColdResCapBonus: 222,
	CrushResCapBonus: 223,
	EnergyResCapBonus: 224,
	HeatResCapBonus: 225,
	MatterResCapBonus: 226,
	SlashResCapBonus: 227,
	SpiritResCapBonus: 228,
	ThrustResCapBonus: 229,
	ResCapBonus_Last: 229,

	DPS: 230,
	MagicAbsorption: 231,
	CriticalHealHitChance: 232,

	// Mythical bonuses
	MythicalSafeFall: 233,
	MythicalDiscumbering: 234,
	MythicalCoin: 235,
	MythicalStatCapBonus_First: 236,
	MythicalStatCapBonus_Last: 244,

	BountyPoints: 247,
	XpPoints: 248,
	Resist_Natural: 249,
	ExtraHP: 250,
	Conversion: 251,
	StyleAbsorb: 252,
	RealmPoints: 253,
	ArcaneSyphon: 254,
	MaxProperty: 255,
} as const;
