export const DaocRealms = [
	{ title: "0. All realms", value: 0 },
	{ title: "1. Albion", value: 1 },
	{ title: "2. Midgard", value: 2 },
	{ title: "3. Hibernia", value: 3 },
];

export const DaocClasses = [
	//base classes
	{ color: "#111", category: "Base", name: "Acolyte", id: 16 },
	{ color: "#111", category: "Base", name: "AlbionRogue", id: 17 },
	{ color: "#111", category: "Base", name: "Disciple", id: 20 },
	{ color: "#111", category: "Base", name: "Elementalist", id: 15 },
	{ color: "#111", category: "Base", name: "Fighter", id: 14 },
	{ color: "#111", category: "Base", name: "Forester", id: 57 },
	{ color: "#111", category: "Base", name: "Guardian", id: 52 },
	{ color: "#111", category: "Base", name: "Mage", id: 18 },
	{ color: "#111", category: "Base", name: "Magician", id: 51 },
	{ color: "#111", category: "Base", name: "MidgardRogue", id: 38 },
	{ color: "#111", category: "Base", name: "Mystic", id: 36 },
	{ color: "#111", category: "Base", name: "Naturalist", id: 53 },
	{ color: "#111", category: "Base", name: "Seer", id: 37 },
	{ color: "#111", category: "Base", name: "Stalker", id: 54 },
	{ color: "#111", category: "Base", name: "Viking", id: 35 },

	//alb classes
	{ color: "#511", category: "Albion", name: "Armsman", id: 2 },
	{ color: "#511", category: "Albion", name: "Cabalist", id: 13 },
	{ color: "#511", category: "Albion", name: "Cleric", id: 6 },
	{ color: "#511", category: "Albion", name: "Friar", id: 10 },
	{ color: "#511", category: "Albion", name: "Heretic", id: 33 },
	{ color: "#511", category: "Albion", name: "Infiltrator", id: 9 },
	{ color: "#511", category: "Albion", name: "Mercenary", id: 11 },
	{ color: "#511", category: "Albion", name: "Minstrel", id: 4 },
	{ color: "#511", category: "Albion", name: "Necromancer", id: 12 },
	{ color: "#511", category: "Albion", name: "Paladin", id: 1 },
	{ color: "#511", category: "Albion", name: "Reaver", id: 19 },
	{ color: "#511", category: "Albion", name: "Scout", id: 3 },
	{ color: "#511", category: "Albion", name: "Sorcerer", id: 8 },
	{ color: "#511", category: "Albion", name: "Theurgist", id: 5 },
	{ color: "#511", category: "Albion", name: "Wizard", id: 7 },
	{ color: "#511", category: "Albion", name: "MaulerAlb", id: 60 },

	//mid classes
	{ color: "#115", category: "Midgard", name: "Berserker", id: 31 },
	{ color: "#115", category: "Midgard", name: "Bonedancer", id: 30 },
	{ color: "#115", category: "Midgard", name: "Healer", id: 26 },
	{ color: "#115", category: "Midgard", name: "Hunter", id: 25 },
	{ color: "#115", category: "Midgard", name: "Runemaster", id: 29 },
	{ color: "#115", category: "Midgard", name: "Savage", id: 32 },
	{ color: "#115", category: "Midgard", name: "Shadowblade", id: 23 },
	{ color: "#115", category: "Midgard", name: "Shaman", id: 28 },
	{ color: "#115", category: "Midgard", name: "Skald", id: 24 },
	{ color: "#115", category: "Midgard", name: "Spiritmaster", id: 27 },
	{ color: "#115", category: "Midgard", name: "Thane", id: 21 },
	{ color: "#115", category: "Midgard", name: "Valkyrie", id: 34 },
	{ color: "#115", category: "Midgard", name: "Warlock", id: 59 },
	{ color: "#115", category: "Midgard", name: "Warrior", id: 22 },
	{ color: "#115", category: "Midgard", name: "MaulerMid", id: 61 },

	//hib classes
	{ color: "#151", category: "Hibernia", name: "Animist", id: 55 },
	{ color: "#151", category: "Hibernia", name: "Bainshee", id: 39 },
	{ color: "#151", category: "Hibernia", name: "Bard", id: 48 },
	{ color: "#151", category: "Hibernia", name: "Blademaster", id: 43 },
	{ color: "#151", category: "Hibernia", name: "Champion", id: 45 },
	{ color: "#151", category: "Hibernia", name: "Druid", id: 47 },
	{ color: "#151", category: "Hibernia", name: "Eldritch", id: 40 },
	{ color: "#151", category: "Hibernia", name: "Enchanter", id: 41 },
	{ color: "#151", category: "Hibernia", name: "Hero", id: 44 },
	{ color: "#151", category: "Hibernia", name: "Mentalist", id: 42 },
	{ color: "#151", category: "Hibernia", name: "Nightshade", id: 49 },
	{ color: "#151", category: "Hibernia", name: "Ranger", id: 50 },
	{ color: "#151", category: "Hibernia", name: "Valewalker", id: 56 },
	{ color: "#151", category: "Hibernia", name: "Vampiir", id: 58 },
	{ color: "#151", category: "Hibernia", name: "Warden", id: 46 },
	{ color: "#151", category: "Hibernia", name: "MaulerHib", id: 62 },
];
