export interface ItemTemplate {
	Id_nb: string; // VARCHAR(255) NOT NULL COLLATE 'utf8mb3_general_ci',
	TranslationId: string | null; // TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	Name: string; // TEXT NOT NULL COLLATE 'utf8mb3_general_ci',
	ExamineArticle: string | null; // TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	MessageArticle: string | null; // TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	Level: number; // INT(11) NOT NULL DEFAULT '0',
	Durability: number; // INT(11) NOT NULL DEFAULT '0',
	MaxDurability: number; // INT(11) NOT NULL DEFAULT '0',
	IsNotLosingDur: number; // TINYINT(1) NOT NULL DEFAULT '0',
	Condition: number; // INT(11) NOT NULL DEFAULT '0',
	MaxCondition: number; // INT(11) NOT NULL DEFAULT '0',
	Quality: number; // INT(11) NOT NULL DEFAULT '0',
	DPS_AF: number; // INT(11) NOT NULL DEFAULT '0',
	SPD_ABS: number; // INT(11) NOT NULL DEFAULT '0',
	Hand: number; // INT(11) NOT NULL DEFAULT '0',
	Type_Damage: number; // INT(11) NOT NULL DEFAULT '0',
	Object_Type: number; // INT(11) NOT NULL DEFAULT '0',
	Item_Type: number; // INT(11) NOT NULL DEFAULT '0',
	Color: number; // INT(11) NOT NULL DEFAULT '0',
	Emblem: number; // INT(11) NOT NULL DEFAULT '0',
	Effect: number; // INT(11) NOT NULL DEFAULT '0',
	Weight: number; // INT(11) NOT NULL DEFAULT '0',
	Model: number; // INT(11) NOT NULL DEFAULT '0',
	Extension: number; // TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	Bonus: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus1: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus2: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus3: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus4: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus5: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus6: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus7: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus8: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus9: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus10: number; // INT(11) NOT NULL DEFAULT '0',
	ExtraBonus: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus1Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus2Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus3Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus4Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus5Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus6Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus7Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus8Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus9Type: number; // INT(11) NOT NULL DEFAULT '0',
	Bonus10Type: number; // INT(11) NOT NULL DEFAULT '0',
	ExtraBonusType: number; // INT(11) NOT NULL DEFAULT '0',
	CanUseEvery: number; // INT(11) NOT NULL DEFAULT '0',
	SpellID: number; // INT(11) NOT NULL DEFAULT '0',
	Charges: number; // INT(11) NOT NULL DEFAULT '0',
	MaxCharges: number; // INT(11) NOT NULL DEFAULT '0',
	SpellID1: number; // INT(11) NOT NULL DEFAULT '0',
	Charges1: number; // INT(11) NOT NULL DEFAULT '0',
	MaxCharges1: number; // INT(11) NOT NULL DEFAULT '0',
	ProcChance: number; // TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	ProcSpellID: number; // INT(11) NOT NULL DEFAULT '0',
	ProcSpellID1: number; // INT(11) NOT NULL DEFAULT '0',
	PoisonSpellID: number; // INT(11) NOT NULL DEFAULT '0',
	PoisonCharges: number; // INT(11) NOT NULL DEFAULT '0',
	PoisonMaxCharges: number; // INT(11) NOT NULL DEFAULT '0',
	IsPickable: number; // TINYINT(1) NOT NULL DEFAULT '0',
	IsDropable: number; // TINYINT(1) NOT NULL DEFAULT '0',
	CanDropAsLoot: number; // TINYINT(1) NOT NULL DEFAULT '0',
	IsTradable: number; // TINYINT(1) NOT NULL DEFAULT '0',
	Price: number; // BIGINT(20) NOT NULL DEFAULT '0',
	MaxCount: number; // INT(11) NOT NULL DEFAULT '0',
	IsIndestructible: number; // TINYINT(1) NOT NULL DEFAULT '0',
	PackSize: number; // INT(11) NOT NULL DEFAULT '0',
	Realm: number; // INT(11) NOT NULL DEFAULT '0',
	AllowedClasses: string; // TEXT NOT NULL COLLATE 'utf8mb3_general_ci',
	Flags: number; // INT(11) NOT NULL DEFAULT '0',
	BonusLevel: number; // INT(11) NOT NULL DEFAULT '0',
	LevelRequirement: number; // INT(11) NOT NULL DEFAULT '0',
	PackageID: string | null; // TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	Description: string | null; // TEXT NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	ClassType: string | null; // VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
	SalvageYieldID: number; // INT(11) NOT NULL DEFAULT '0',
	LastTimeRowUpdated: string; // DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00',
	ItemTemplate_ID: string | null; // VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb3_general_ci',
}
