export class NpcTemplate {
	NpcTemplate_ID?: string;

	TemplateId: number = -1;
	Name: string = "New MerchantItem Template";
	GuildName?: string;
	Model: string = "480";
	Size: string = "50";
	MaxSpeed: number = 200;
	EquipmentTemplateID?: string;
	Flags: number = 16;
	MeleeDamageType: number = 2;
	ParryChance: number = 0;
	EvadeChance: number = 0;
	BlockChance: number = 0;
	LeftHandSwingChance: number = 0;
	Spells?: string;
	Styles?: string;
	Strength: number = 0;
	Constitution: number = 0;
	Dexterity: number = 0;
	Quickness: number = 0;
	Intelligence: number = 0;
	Piety: number = 0;
	Charisma: number = 0;
	Empathy: number = 0;
	WeaponDps: number = 0;
	WeaponSpd: number = 0;
	ArmorFactor: number = 0;
	ArmorAbsorb: number = 0;
	Abilities?: string;
	AggroLevel: number = 0;
	AggroRange: number = 0;
	ClassType: string = "AmteMob";
	Level: string = "1";
	Race: number = 0;
	BodyType: number = 0;
	MaxDistance: number = 0;
	TetherRange: number = 0;
	PackageID: string = "AmteManager";
	VisibleWeaponSlots: number = 0;
	ReplaceMobValues: boolean = true;
	ItemsListTemplateID?: string;
	TranslationId?: string;
	Suffix?: string;
	ExamineArticle?: string;
	MessageArticle?: string;
	Gender: number = 0;
	LastTimeRowUpdated: string = "2000-01-01 00:00:00";
	BreamorFaction: number = 0;
}
